export const dataGaleriFoto = [
  {
    title: "KPU Ucapkan Terima Kasih Atas Kinerja PPK dan PPS",
    date: "10 Oktober 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["Pemilu 2020", "Arsip"],
  },
  {
    title: "KPU Ucapkan Terima Kasih Atas Kinerja PPK dan PPS",
    date: "10 Oktober 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["Pemilu 2020", "Arsip"],
  },
  {
    title: "KPU Ucapkan Terima Kasih Atas Kinerja PPK dan PPS",
    date: "10 Oktober 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["Pemilu 2020", "Arsip"],
  },
  {
    title: "KPU Ucapkan Terima Kasih Atas Kinerja PPK dan PPS",
    date: "10 Oktober 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["Pemilu 2020", "Arsip"],
  },
  {
    title: "KPU Ucapkan Terima Kasih Atas Kinerja PPK dan PPS",
    date: "10 Oktober 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["Pemilu 2020", "Arsip"],
  },
  {
    title: "KPU Ucapkan Terima Kasih Atas Kinerja PPK dan PPS",
    date: "10 Oktober 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["Pemilu 2020", "Arsip"],
  },
  {
    title: "KPU Ucapkan Terima Kasih Atas Kinerja PPK dan PPS",
    date: "10 Oktober 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["Pemilu 2020", "Arsip"],
  },
  {
    title: "KPU Ucapkan Terima Kasih Atas Kinerja PPK dan PPS",
    date: "10 Oktober 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["Pemilu 2020", "Arsip"],
  },
];

export const dataGaleriFotoEn = [
  {
    title: "KPU Thanks PPK and PPS for Their Work",
    date: "October 10, 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["2020 Election", "Archive"],
  },
  {
    title: "KPU Thanks PPK and PPS for Their Work",
    date: "October 10, 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["2020 Election", "Archive"],
  },
  {
    title: "KPU Thanks PPK and PPS for Their Work",
    date: "October 10, 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["2020 Election", "Archive"],
  },
  {
    title: "KPU Thanks PPK and PPS for Their Work",
    date: "October 10, 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["2020 Election", "Archive"],
  },
  {
    title: "KPU Thanks PPK and PPS for Their Work",
    date: "October 10, 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["2020 Election", "Archive"],
  },
  {
    title: "KPU Thanks PPK and PPS for Their Work",
    date: "October 10, 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["2020 Election", "Archive"],
  },
  {
    title: "KPU Thanks PPK and PPS for Their Work",
    date: "October 10, 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["2020 Election", "Archive"],
  },
  {
    title: "KPU Thanks PPK and PPS for Their Work",
    date: "October 10, 2024",
    imgSrc: "/images/GaleriFoto1.png",
    filepath: "/images/GaleriFoto1.png",
    views: 666,
    size: "1.5 MB",
    tags: ["2020 Election", "Archive"],
  },
];

export const dataGaleriVideo = [
  {
    title: "Tata Cara Pencoblosan Pemilihan Umum 2024",
    date: "10 Oktober 2024",
    imgSrc: "/images/GaleriVideo1.jpg",
    filepath: "/videos/GaleriVideo1.mp4",
    views: 666,
    size: "12.5 MB",
    tags: ["Pemilu 2024", "Tutorial"],
  },
  {
    title: "Tata Cara Pencoblosan Pemilihan Umum 2024",
    date: "10 Oktober 2024",
    imgSrc: "/images/GaleriVideo1.jpg",
    filepath: "/videos/GaleriVideo1.mp4",
    views: 666,
    size: "12.5 MB",
    tags: ["Pemilu 2024", "Tutorial"],
  },
  {
    title: "Tata Cara Pencoblosan Pemilihan Umum 2024",
    date: "10 Oktober 2024",
    imgSrc: "/images/GaleriVideo1.jpg",
    filepath: "/videos/GaleriVideo1.mp4",
    views: 666,
    size: "12.5 MB",
    tags: ["Pemilu 2024", "Tutorial"],
  },
  {
    title: "Tata Cara Pencoblosan Pemilihan Umum 2024",
    date: "10 Oktober 2024",
    imgSrc: "/images/GaleriVideo1.jpg",
    filepath: "/videos/GaleriVideo1.mp4",
    views: 666,
    size: "12.5 MB",
    tags: ["Pemilu 2024", "Tutorial"],
  },
];

export const dataGaleriVideoEn = [
  {
    title: "Voting Procedures for the 2024 General Election",
    date: "October 10, 2024",
    imgSrc: "/images/GaleriVideo1.jpg",
    filepath: "/videos/GaleriVideo1.mp4",
    views: 666,
    size: "12.5 MB",
    tags: ["2024 Election", "Tutorial"],
  },
  {
    title: "Voting Procedures for the 2024 General Election",
    date: "October 10, 2024",
    imgSrc: "/images/GaleriVideo1.jpg",
    filepath: "/videos/GaleriVideo1.mp4",
    views: 666,
    size: "12.5 MB",
    tags: ["2024 Election", "Tutorial"],
  },
  {
    title: "Voting Procedures for the 2024 General Election",
    date: "October 10, 2024",
    imgSrc: "/images/GaleriVideo1.jpg",
    filepath: "/videos/GaleriVideo1.mp4",
    views: 666,
    size: "12.5 MB",
    tags: ["2024 Election", "Tutorial"],
  },
  {
    title: "Voting Procedures for the 2024 General Election",
    date: "October 10, 2024",
    imgSrc: "/images/GaleriVideo1.jpg",
    filepath: "/videos/GaleriVideo1.mp4",
    views: 666,
    size: "12.5 MB",
    tags: ["2024 Election", "Tutorial"],
  },
];
